Caching responses
willianjusten/nba-remix pull request #72
Opened 2022-03-07 15:43 UTC by gustavoguichard

For even snappier UX.

[Reference](https://www.youtube.com/watch?v=bfLFHp7Sbkg)

![pr2](https://user-images.githubusercontent.com/566971/157065869-b48c5406-5bb3-48be-aa1f-584b621b6145.gif)

I don't have a complete understanding of NBA's API and want to see your ideas on this but we could make `app/routes/$date` route return a long cache for past games, light cache for active games and medium for future games.

I'll explain my caching decisions on comments through the diff, opinions on it are welcome.

2022-03-07 15:45 UTC, gustavoguichard commented on app/routes/game/$year/$gameId.tsx
> +          'public, max-age=1, s-maxage=60, stale-while-revalidate=31540000000',
cache for 60s on CDN and always deliver cached result for next visitor (SWR)

2022-03-07 15:45 UTC, gustavoguichard commented on app/routes/index.tsx
> +          'public, max-age=1, s-maxage=30, stale-while-revalidate=31540000000',
cache for 30s on CDN and always deliver cached result for next visitor (SWR)

2022-03-07 15:45 UTC, gustavoguichard commented on app/routes/standings.tsx
> +          'public, max-age=60, s-maxage=600, stale-while-revalidate=31540000000',
cache on browsers for a minute, on CDN for 10min and always deliver cached result for next visitor (SWR)

2022-03-07 15:46 UTC, gustavoguichard commented on app/routes/index.tsx
> +          'public, max-age=1, s-maxage=30, stale-while-revalidate=31540000000',
Maybe this could also be cached on user browser

2022-03-07 15:47 UTC, gustavoguichard commented on app/routes/$date.tsx
> +          'public, max-age=1, s-maxage=30, stale-while-revalidate=31540000000',
This could have different cache strategies for both past, active and future games

2022-03-07 15:47 UTC, gustavoguichard commented
It'd be good to allow the vercel deployment preview for a better QA ;)

2022-03-07 17:07 UTC, gustavoguichard reviewed
@helderburato what do you think?

I spent some time trying to test but MSW won't let me do a unit test here. Anyone have ideas on how to disable MSW for this file?

2022-03-07 17:32 UTC, helderburato commented on app/routes/$date.tsx
> +          'public, max-age=1, s-maxage=30, stale-while-revalidate=31540000000',
Feel free to take another approach, it's just a suggestion.

2022-03-07 17:32 UTC, willianjusten commented
Hey @gustavoguichard , thanks for another great PR, I'll have a look at the end of the day and then I can give some feedback =D

2022-03-07 17:35 UTC, helderburato commented
> 

Can you share more details about the error? I think it's because the MSW is in the global scope of every test.

---

About the abstraction, it feels good for me. What do you think @willianjusten?

2022-03-07 20:59 UTC, willianjusten commented
Hey @gustavoguichard that's indeed something very interesting to have, and thanks for showing me the video, very insightful! 
So, some details that we need to have in mind here:

Since we use [useRevalidateOnInterval](https://github.com/willianjusten/nba-remix/blob/main/app/hooks/use-revalidate-on-interval.ts) hook to revalidate and refresh the page to get the new data in a "near realtime", we just need to take care about the time we're going to refetch and the time that we are going to cache, if not, we can get "stale" data, that it's not the desired state.

For now, what we have, is:

-  `index` - our home refetches every [20 seconds](https://github.com/willianjusten/nba-remix/blob/main/app/constants.ts#L107)
- `game/$year/$gameId` - does the same, as we need to show the player stats and the score as well
- `$date` - definitely can be cached for longer period, but we need to check against the date that is exactly Today, because in this case, we don't want to have stale data also
- `standings` this one can be cached for a longer period, since it doesn't change that much.

I think only the ones that we need this "real time" we can change to 20s, the others we can have some bigger caching time, without problems.

---

About the code, I liked the abstraction, looks clean and readable, with the comments, got even better. I'd just ask to get the "magical numbers" of time to cache and put them to the [constants](https://github.com/willianjusten/nba-remix/blob/main/app/constants.ts) file.

2022-03-07 21:00 UTC, willianjusten requested changes
Just change few things that I commented and it will be ready to merge =D

2022-03-07 22:34 UTC, gustavoguichard commented
Hey @willianjusten thanks for taking the time and changing it. I wanted to propose the changes but was sure you guys would have a better idea about the caching times.
Shall we merge it?

2022-03-08 02:43 UTC, gustavoguichard commented
Thanks for the directions. I'm not gonna have much time to contribute in the next couple days.
I set every cache to 20s, only leaving the `standings` to 10min on the CND.
If you feel like this is going to bring benefits in the next few days feel free to merge it, otherwise I'll improve it soon ;)

2022-03-09 10:11 UTC, helderburato approved these changes
🚀

2022-03-09 16:19 UTC, helderburato commented
Is this already done to be merged?

2022-03-09 16:25 UTC, gustavoguichard commented
Hey @helderburato , still didn't have time to go further. I think it brings value already but if you guys don't merge it I'll be doing the changes within the next couple days

2022-03-09 16:39 UTC, willianjusten commented
I have to say it's good to merge yet and after you can open another PR if you want =)

2022-03-09 16:39 UTC, willianjusten approved these changes

2022-03-09 16:40 UTC, merged