Add validate run on CI - closes #81
willianjusten/nba-remix pull request #82
Opened 2022-03-10 15:13 UTC by helderburato

2022-03-10 17:06 UTC, willianjusten requested changes
Looks good, just adjust some details.

2022-03-10 17:06 UTC, willianjusten commented on .github/workflows/ci.yml
> +        node: [12, 14]
Any reason of using both node versions? I'd use only one, there's no need to run twice, we're not releasing anything that needs to be compatible to different node versions.

2022-03-10 17:06 UTC, willianjusten commented on README.md
> +## NBA Remix
Oh, thanks for fixing the name here xD

2022-03-10 17:06 UTC, willianjusten commented on package.json
> +    "validate": "npm run lint && npm run test:ci"
I see you creating this but not using anywhere, maybe we should remove it?

2022-03-10 17:16 UTC, adeonir commented on .github/workflows/ci.yml
> +        node: [12, 14]
We can stick with version 14, which is the latest LTS running on Vercel.

2022-03-10 17:26 UTC, helderburato commented on package.json
> +    "validate": "npm run lint && npm run test:ci"
I forgot to remove this one, nice catch!

2022-03-10 17:31 UTC, helderburato commented on .github/workflows/ci.yml
> +        node: [12, 14]
Updated to keep the version `14`.

2022-03-11 00:56 UTC, willianjusten approved these changes
Great =)

2022-03-11 01:23 UTC, adeonir approved these changes

2022-03-11 08:55 UTC, merged